var myString;
var myNum;
var myBool;
var myVar;
var strArr;
var numArr;
var boolArr;
// let strArr: Array<string>;
// let numArr: Array<number>;
// let boolArr: Array<boolean>;
var strNumTuple;
myString = 'Hello'.slice(0, 3);
myNum = 1;
myBool = false;
myVar = true;
strArr = ['Hello', 'World'];
numArr = [1, 2, 3];
boolArr = [true, false, true];
strNumTuple = ['Hello', 4];
var myVoid = undefined;
var myNull = null;
var myUndefined = null;
console.log(strArr);
